module.exports = {
  type: 'Form',
  expanded: true,
  items: [{
    type: 'Layout',
    expanded: false,
    items: [{
      type: 'Group'
    }, {
      type: 'Group'
    }]
  }, {
    type: 'ToolBar',
    expanded: false,
    items: [{
      type: 'Tool',
      expanded: false,
      items: [{
        type: 'Tool'
      }]
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'Tool'
    }, {
      type: 'qqqqqqqqqqqqqqqqqq'
    }]
  }]
};
