module.exports = {
  type: 'Form',
  expanded: true,
  items: [{
    type: 'Layout',
    expanded: false,
    items: [{
      type: 'Group'
    }, {
      type: 'Group'
    }]
  }, {
    type: 'ToolBar',
    expanded: false,
    items: [{
      type: 'Tool',
      expanded: false,
      items: [{
        type: 'Tool'
      }]
    }, {
      type: '1Tool',
      properties: {
        caption: 'tool1',
        img: '/path/path/path/img.jpg'
      }
    }, {
      type: '2Tool'
    }, {
      type: '3Tool'
    }, {
      type: '4Tool'
    }, {
      type: '5Tool'
    }, {
      type: '6Tool'
    }, {
      type: '7Tool'
    }, {
      type: '8Tool'
    }, {
      type: '9Tool'
    }, {
      type: '10Tool'
    }, {
      type: '11Tool'
    }, {
      type: '12Tool'
    }, {
      type: '13Tool'
    }, {
      type: '14Tool'
    }, {
      type: '15Tool'
    }, {
      type: '16Tool'
    }, {
      type: '17Tool'
    }, {
      type: '18Tool'
    }, {
      type: '19Tool'
    }, {
      type: '20Tool'
    }, {
      type: '21Tool'
    }, {
      type: '22Tool'
    }, {
      type: '23Tool'
    }, {
      type: '24Tool'
    }, {
      type: '25Tool'
    }, {
      type: '26Tool'
    }, {
      type: '27Tool'
    }, {
      type: '28Tool'
    }, {
      type: '29Tool'
    }, {
      type: '30Tool'
    }, {
      type: '31Tool'
    }, {
      type: '32Tool'
    }, {
      type: '33Tool'
    }, {
      type: '34Tool'
    }, {
      type: '35Tool'
    }]
  }]
};
